ChromaStyle = "github"
MermaidTheme = "default"

Background = "#e8e9ec"
Foreground = "#33374c"
BackgroundAlt = "#dcdfe7"
Comment = "#8389a3"
CurrentLine = "#dcdfe7"
Selection = "#c9cdd7"
LineNumber = "#9fa7bd"
LineNumberActive = "#576a9e"

Red = "#cc517a"
Orange = "#c57339"
Yellow = "#eac6ad"
Green = "#668e3d"
Cyan = "#3f83a6"
Blue = "#2d539e"
Purple = "#7759b4"

Link = "#3f83a6"
LinkHover = "#2d539e"
CodeBg = "#dcdfe7"
CodeFg = "#33374c"
BorderColor = "#cad0de"
