ChromaStyle = "nord"
MermaidTheme = "dark"

Background = "#161821"
Foreground = "#c6c8d1"
BackgroundAlt = "#1e2132"
Comment = "#6b7089"
CurrentLine = "#1e2132"
Selection = "#272c42"
LineNumber = "#444b71"
LineNumberActive = "#cdd1e6"

Red = "#e27878"
Orange = "#e2a478"
Yellow = "#e4aa80"
Green = "#b4be82"
Cyan = "#89b8c2"
Blue = "#84a0c6"
Purple = "#a093c7"

Link = "#89b8c2"
LinkHover = "#84a0c6"
CodeBg = "#1e2132"
CodeFg = "#c6c8d1"
BorderColor = "#0f1117"
